### ISSUE TITLE
chore(protocol/registry): Silent Deserialization Failures

### ISSUE THREAD

**Issue by refcell** [op-rs/kona#1047]
### Description

When encountering unknown fields, serde will not error by default.

For example, if the data format in the [superchain-registry](https://github.com/ethereum-optimism/superchain-registry) changes, the toml deserialization can silently fail. Let's say a new hardfork was added to a chain config.

```toml
[hardforks]
  canyon_time = 1704992401 # Thu 11 Jan 2024 17:00:01 UTC
  delta_time = 1708560000 # Thu 22 Feb 2024 00:00:00 UTC
  ecotone_time = 1710374401 # Thu 14 Mar 2024 00:00:01 UTC
  fjord_time = 1720627201 # Wed 10 Jul 2024 16:00:01 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC
  new_hardfork = 1777777777
```

Deserializing this into the [HardForkConfiguration struct](https://github.com/op-rs/maili/blob/main/crates/genesis/src/chain/hardfork.rs#L6C1-L26C2).

```rust
#[derive(Debug, Copy, Clone, Default, Hash, Eq, PartialEq)]
#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct HardForkConfiguration {
    /// Canyon hardfork activation time
    pub canyon_time: Option<u64>,
    /// Delta hardfork activation time
    pub delta_time: Option<u64>,
    /// Ecotone hardfork activation time
    pub ecotone_time: Option<u64>,
    /// Fjord hardfork activation time
    pub fjord_time: Option<u64>,
    /// Granite hardfork activation time
    pub granite_time: Option<u64>,
    /// Holocene hardfork activation time
    pub holocene_time: Option<u64>,
    /// Isthmus hardfork activation time
    pub isthmus_time: Option<u64>,
    /// Interop hardfork activation time
    pub interop_time: Option<u64>,
}
```

This will not fail and produce the following `HardForkConfiguration`:

```rust
let deserialized = HardForkConfiguration {
    canyon_time: Some(1704992401),
    delta_time: Some(1708560000),
    ecotone_time: Some(1710374401),
    fjord_time: Some(1720627201),
    granite_time: Some(1726070401),
    holocene_time: Some(1736445601),
    isthmus_time: None,
    interop_time: None,
};
```

Notice that the `new_hardfork` field is ignored.

#### Output

Serde provides a container attribute [`#[serde(deny_unknown_fields)]`](https://serde.rs/container-attrs.html#deny_unknown_fields) that will error when encountering unknown fields. Structs in the registry need to be updated with the `deny_unknown_fields` container attribute so that when the `superchain-registry` submodule is updated, deserialization tests will fail if an unknown field is present. That will force the registry types to be fixed when the `superchain-registry` is updated.
